import type {
  SoulboundMembershipProof,
  SoulboundProofVerificationResult,
} from "@adasouls/soulbound-core";
import type { SoulboundProvider } from "./providers/types.js";

export interface AccessCheckResult {
  /** true if the wallet has a valid, non-expired credential for the resource */
  hasAccess: boolean;
  /** "MEMBER", "TRIAL", or another level defined by the issuing organization */
  accessLevel?: string;
  /** Unix timestamp of expiration. undefined = never expires. */
  expiresAt?: number;
  /** true if access is a trial — use to show banners or paywalls */
  isTrial: boolean;
}

export class SoulboundVerifier {
  constructor(private readonly provider: SoulboundProvider) {}

  /**
   * Cryptographically verify a ZK Proof generated by SoulboundHolder.generateProof().
   * Use in gates where the verifier does NOT have access to the user's wallet.
   */
  async verifyProof(
    proof: SoulboundMembershipProof
  ): Promise<SoulboundProofVerificationResult> {
    return this.provider.verifyProof(proof);
  }

  /**
   * Check if a wallet has valid access to a given resource.
   *
   * This is the main gate for applications.
   * Unlike verifyProof(), it operates directly on the provider state
   * (useful when the verifier controls the user session).
   *
   * @example
   *   const { hasAccess, isTrial, expiresAt } = await verifier.checkAccess(
   *     walletAddress,
   *     { resourceId: "my-game:main", orgId: "some-policy-id" }
   *   );
   *
   *   if (!hasAccess) return showTrialOffer();
   *   if (isTrial) showTrialBanner({ expiresAt });
   *   startGame();
   */
  async checkAccess(
    walletAddress: string,
    options: { resourceId: string; orgId?: string }
  ): Promise<AccessCheckResult> {
    const walletHash = this.provider.hashWalletAddress(walletAddress);
    const all = await this.provider.listByWalletHash(walletHash);
    const nowSecs = Math.floor(Date.now() / 1000);

    const valid = all.find(({ credential }) => {
      if (credential.status !== "CLAIMED") return false;
      if (credential.expiresAt !== undefined && credential.expiresAt <= nowSecs) return false;
      if (options.orgId !== undefined && credential.issuer.orgId !== options.orgId) return false;
      return credential.subject.metadata?.["resourceId"] === options.resourceId;
    });

    if (valid === undefined) {
      return { hasAccess: false, isTrial: false };
    }

    const level = valid.credential.subject.metadata?.["accessLevel"];
    const accessLevel = typeof level === "string" ? level : undefined;

    const result: AccessCheckResult = {
      hasAccess: true,
      isTrial: accessLevel === "TRIAL",
    };
    if (accessLevel !== undefined) result.accessLevel = accessLevel;
    if (valid.credential.expiresAt !== undefined) result.expiresAt = valid.credential.expiresAt;
    return result;
  }
}
