// Soulbound Protocol — Core Type Definitions
// Source of truth for the standard. All SDK and contracts derive from these types.
// Maintained by AdaSouls Labs.

// ─── Issuing Organization ────────────────────────────────────────────────────

export type SoulboundOrgType =
  | "DAO"          // Decentralized autonomous organization
  | "CLUB"         // Sports, social, cultural club
  | "HOSPITAL"     // Hospital, clinic, medical center
  | "UNIVERSITY"   // University, academy, institute
  | "CORP"         // Private company (employees, partners)
  | "COOPERATIVE"  // Cooperative, union
  | "GOVERNMENT"   // Government agency
  | "OTHER";

export interface SoulboundIssuer {
  orgId: string;          // PolicyId of the issuer on Cardano
  orgName: string;        // e.g. "ALDEA DAO"
  orgType: SoulboundOrgType;
  publicKey: string;      // Issuer's public key (signature verification)
}

// ─── Credential ──────────────────────────────────────────────────────────────

export type SoulboundCredentialStatus =
  | "PENDING"   // Issued by org, not yet claimed by holder
  | "CLAIMED"   // Claimed by holder
  | "REVOKED"   // Revoked by issuer
  | "EXPIRED";  // Expired (expiresAt < now)

export type SoulboundSchemaId =
  | "soulbound:v1:membership"    // General organization membership
  | "soulbound:v1:certificate"   // Achievement/completion certificate
  | "soulbound:v1:professional"  // Professional credential
  | "soulbound:v1:access";       // Service/platform access credential

export interface SoulboundCredential {
  // Schema identification
  schemaId: SoulboundSchemaId;
  schemaVersion: string;         // "1.0.0"

  // Issuing organization
  issuer: SoulboundIssuer;

  // Holder data (shielded in Midnight — never exposed publicly)
  subject: {
    walletHash: string;          // Hash of the wallet (not the public address)
    usernameHash?: string;       // SHA-256 hash of username (selectively disclosable)
    memberId?: string;           // Internal org ID (encrypted)
    metadata?: Record<string, unknown>; // Extra data (shielded)
  };

  // Validity
  issuedAt: number;              // Unix timestamp
  expiresAt?: number;            // Unix timestamp (undefined = never expires)

  // Status
  status: SoulboundCredentialStatus;

  // Fields the holder can selectively disclose in a ZK Proof
  disclosureFields: string[];

  // Issuer's signature over the credential hash
  credentialProof: string;
}

// ─── Standard Schemas ────────────────────────────────────────────────────────

export interface SoulboundSchemaDefinition {
  schemaId: SoulboundSchemaId;
  requiredFields: string[];
  optionalFields: string[];
  disclosableFields: string[];   // Subset the holder can reveal
}

export const SOULBOUND_SCHEMAS: Record<SoulboundSchemaId, SoulboundSchemaDefinition> = {
  "soulbound:v1:membership": {
    schemaId: "soulbound:v1:membership",
    requiredFields: ["orgId", "walletHash", "issuedAt"],
    optionalFields: ["memberId", "memberSince", "tier", "expiresAt", "usernameHash"],
    disclosableFields: ["orgId", "memberSince", "tier", "usernameHash"],
  },
  "soulbound:v1:certificate": {
    schemaId: "soulbound:v1:certificate",
    requiredFields: ["orgId", "walletHash", "achievementName", "issuedAt"],
    optionalFields: ["grade", "courseId", "validUntil"],
    disclosableFields: ["orgId", "achievementName", "issuedAt"],
  },
  "soulbound:v1:professional": {
    schemaId: "soulbound:v1:professional",
    requiredFields: ["orgId", "walletHash", "professionCode", "licenseNumber", "issuedAt"],
    optionalFields: ["specialty", "validUntil", "issuingAuthority"],
    disclosableFields: ["professionCode", "licenseNumber", "issuingAuthority"],
  },
  "soulbound:v1:access": {
    schemaId: "soulbound:v1:access",
    requiredFields: ["orgId", "walletHash", "resourceId", "issuedAt"],
    optionalFields: ["accessLevel", "expiresAt", "usernameHash"],
    disclosableFields: ["resourceId", "accessLevel", "usernameHash"],
  },
} as const;

// ─── ZK Proofs ───────────────────────────────────────────────────────────────

export interface SoulboundMembershipProof {
  // The proof itself (opaque — generated by Midnight ZK circuit)
  proofData: string;

  // Fields selectively disclosed by the holder
  disclosedFields: Record<string, unknown>;

  // Proof metadata (contains no holder data)
  resourceId: string;      // The resource being accessed
  expectedOrgId: string;   // PolicyId of the expected issuer
  nonce: string;           // Prevents replay attacks
  generatedAt: number;     // Unix timestamp
}

export interface SoulboundProofVerificationResult {
  isValid: boolean;
  orgId?: string;           // Only if disclosed
  resourceId: string;
  verifiedAt: number;
}

// ─── Emit/Mint Input ─────────────────────────────────────────────────────────

export interface SoulboundEmitInput {
  schema: SoulboundSchemaId;
  subject: {
    walletAddress: string;   // Public address (hashed internally before storing)
    username?: string;       // Plaintext username (hashed internally before storing)
    resourceId?: string;     // For "soulbound:v1:access" schema
    accessLevel?: string;    // For "soulbound:v1:access" schema
    memberId?: string;
    memberSince?: number;
    tier?: string;
    achievementName?: string;
    grade?: string;
    courseId?: string;
    professionCode?: string;
    licenseNumber?: string;
    specialty?: string;
    issuingAuthority?: string;
  };
  expiresAt?: Date;
}

// ─── Public Mint (ADA payment) ───────────────────────────────────────────────

export interface SoulboundPublicMintRequest {
  walletAddress: string;
  paymentTxHash: string;     // Cardano payment tx hash
  paymentAmount: bigint;     // In Lovelace
}

export interface SoulboundPublicMintResult {
  credentialId: string;
  txHash: string;            // Midnight issuance tx
  status: "PENDING";
}

// ─── IDs ─────────────────────────────────────────────────────────────────────

// Format: "soulbound:cred:<contract-address>:<index>"
export type SoulboundCredentialId = `soulbound:cred:${string}`;

// Format: "soulbound:proof:<nonce>"
export type SoulboundProofId = `soulbound:proof:${string}`;
